### ISSUE TITLE
Spotlight finds two entities but CBC module ignore it

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/core#23]
When ENSEPRO do a call to Spotlight to process the question below, the last find 2 entities but the former ignore them.
- Quem é o compositor da trilha sonora do **_Titanic_** de **_Cameron_**?

Log file: [ensepro.log](https://github.com/Ensepro/core/files/2474093/ensepro.log)

**Comment by alencarrh** [comment]
This is no an issue/bug. This situation was not implemented yet.

See issue #10.
