### ISSUE TITLE
The type of the TR must be considered when calculating the metrics

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/core#33]
Today the algorithm to calculate the metrics only look to the strings, disregarding about the class of the match.
The metrics calculation algorithm must consider that:
1. Proper nouns (and its derivations) are only subject or object of the triple
2. Verbs (and its derivations) are only predicates
3. Common nouns (and its derivations) can be subject, predicate or object

The problem was noticed in the question:
- Christian Bale atuou em Batman Begins?

The disregarding of the class produced several incorrect matchings:
> 0 - score:27.500 [+christian_bale | ocupacao | +**ator** | +batman_begins | elenco | +christian_bale]   metrics: [26.000 0.500 1.000]
> 1 - score:24.660 [+termin**ator**_salvation | elenco | +christian_bale | +batman_begins | elenco | +christian_bale]   metrics: [23.160 0.500 1.000]
> 2 - score:24.660 [+batman_begins | elenco | +christian_bale | +termin**ator**_salvation | elenco | +christian_bale]   metrics: [23.160 0.500 1.000]
> 3 - score:24.133 [+christian_bale | oscaresacademia | +melhor **ator** coadjuvante | +batman_begins | elenco | +christian_bale]   metrics: [22.633 0.500 1.000]
> 4 - score:24.133 [+christian_bale | nationalboardofreview | +melhor **ator** coadjuvante | +batman_begins | elenco | +christian_bale]   metrics: [22.633 0.500 1.000]
> 5 - score:24.133 [+christian_bale | sagawards | +melhor **ator** coadjuvante | +batman_begins | elenco | +christian_bale]   metrics: [22.633 0.500 1.000]

**Comment by alencarrh** [comment]
@DenisAraujo68 can you please check if the fix resolved the issue?
