### ISSUE TITLE
Novo cálculo de ranqueamento com critério único

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/core#7]
## Métrica 1 - soma dos pesos modularizados dos TRs

- **peso_classe_gram_TR x len(TR) / { len(TR) - 1 + 1,1 ^ [len(match)-len(TR)] }** 
- o peso da classe gramatical da TR precisa ser modularizado pela distância de Levenshtein entre o TR e o match encontrado
- este cálculo vai fazer com que matches não significativos diminuam o peso da classe gram. 
- Ex.: abraham_lincoln => ['*abraham_lincoln'] = 10 × 15 / (14 + 1,1 ^ (15-15)) = 10
- Ex.: morte => ['*datamorte'] = 10 × 5 / (4 + 1,1 ^ (9-5)) = 9,150637799
- Ex.: james_bond => ['*lista_de_romances_e_contos_de_james_bond'] = 10 × 10 / (9 + 1,1 ^ (40-10)) = 3,780803777

## Métrica 2: número de matches proporcionais ao tamanho da tripla
- **qtde_match_tripla / qtde_elem_tripla (qto maior, melhor)**
- é preciso equacionar a importancia dos matches em triplas simples e pares de triplas
- este cálculo vai fazer com que triplas simples com matches simples sejam valorizados em relação aos matches em pares de triplas
- **IMPORTANTE**: os matches de TR contam sempre 1 única vez
- Ex.: ['+batman_begins', 'elenco', '+christian_bale'] = 2 / 3 = 0,6667
- Ex.: ['+christian_bale', 'ocupacao', '+ator'], ['+batman_begins', 'elenco', '+christian_bale'] = 3 / 6 = 0,5

## Métrica 3 - percentual de substantivos próprios encontrados na resposta
- qtde_PROPs_resposta / qtde_PROPs_pergunta
- a quantidade de nomes próprios encontrados na resposta é fator essencial para avaliar se a resposta é ou não a resposta correta
- Frase: Christian Bale atuou no filme Batman Begins?
- ['+batman_begins', 'elenco', '+christian_bale'] = 2 / 1 = 1
- ['+christian_bale', 'ocupacao', '+ator'], ['+batman_begins', 'elenco', '+christian_bale'] = 2 / 2

## Métrica 4 - rank retornado pelo ES
- **IMPORTANTE:** como desconheço o valor atual, ainda não sei exatamente como usá-lo.

## Fórmula do Ranque único de classificação
- RANQUE = M1 x PM1 + M2 x PM2 + M3 x PM3 + M4 x PM4
- Mn = métrica n
- PMn = peso métrica n

## Formato da saída
[
      ['suj', 'pred', 'obj'],  
      rank: RANQUE. 
      [Metr: M1, M2, M3, M4], 
      [PesosMetr: PM1,PM2,PM3,PM4], 
      [pesoClasses: peso_clas_gram1, peso_clas_gramN, ...], 
      [lenTR: lenTR1, lenTRn, ...], 
      [lenMatches: lenMatchTR1, lenMatchTRn, ... ], 
      qtMatches: 99,  
      qtElemTrip: 99, 
      qtPROPs: 99, 
      qtPROPmatch: 99
]

**Comment by alencarrh** [comment]
done
